apiVersion: v1
kind: Service
metadata:
  name: project-task-service
  labels:
    app: project-task
spec:
  selector:
    app: project-task
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP